# Generated by Django 4.2.13 on 2024-07-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_llmfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='input_alert',
            field=models.TextField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('EQUAL', 'EQUAL')], default='EQUAL', verbose_name='input_alert'),
        ),
        migrations.AddField(
            model_name='alert',
            name='output_alert',
            field=models.TextField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('EQUAL', 'EQUAL')], default='EQUAL', verbose_name='output_alert'),
        ),
        migrations.AlterField(
            model_name='llminteraction',
            name='input_metric',
            field=models.IntegerField(verbose_name='input_metric'),
        ),
        migrations.AlterField(
            model_name='llminteraction',
            name='output_metric',
            field=models.IntegerField(verbose_name='output_metric'),
        ),
    ]
