# Generated by Django 4.2.13 on 2024-07-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_alert_input_alert_alert_output_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llminteraction',
            name='input_metric',
            field=models.IntegerField(default=0, verbose_name='input_metric'),
        ),
        migrations.AlterField(
            model_name='llminteraction',
            name='output_metric',
            field=models.IntegerField(default=0, verbose_name='output_metric'),
        ),
    ]
